name: Sync pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Gradle
        uses: ./.github/actions/setup_gradle
      - name: Run the task
        run: |
          ./gradlew \
          :fabric:1.18.2:modrinthSyncBody
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
